[wokwi]
version = 1
# Exercise
firmware = 'target/xtensa-esp32-espidf/debug/test-rust-esp'
elf = 'target/xtensa-esp32-espidf/debug/test-rust-esp'

# Solution - HTTP
# firmware = 'target/riscv32imc-esp-espidf/debug/examples/http_client'
# elf = 'target/riscv32imc-esp-espidf/debug/examples/http_client'